name: Construcci贸n y despliegue de una aplicaci贸n MVC a Azure 

env:
  AZURE_WEBAPP_NAME: upt-awa-320  # Nombre de tu aplicaci贸n en Azure
  DOTNET_VERSION: '8'             # Versi贸n de .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # necesario para GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      user_lower: ${{ steps.set-user-lower.outputs.user_lower }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set lowercase user
        id: set-user-lower
        run: echo "user_lower=$(echo '${GITHUB_ACTOR}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        run: |
          docker build . --tag ghcr.io/${{ steps.set-user-lower.outputs.user_lower }}/shorten:${GITHUB_SHA}
          docker push ghcr.io/${{ steps.set-user-lower.outputs.user_lower }}/shorten:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ghcr.io/${{ needs.build.outputs.user_lower }}/shorten:${{ github.sha }}
